# Generated by Django 5.2.2 on 2025-06-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_post',
            old_name='topic',
            new_name='blog',
        ),
    ]
